// Generated by the Ownly monorepo export - deterministic build stamp.
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const version = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).version;
const content = "// Auto-generated at build time - do not edit\nexport const GIT_SHA = '" + version + "';\n";
writeFileSync(join(root, 'src', 'core', 'git-sha.ts'), content, 'utf8');
console.log('Build stamp (version): ' + version);
